apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-disk
  namespace: todo-app
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi