apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: todo-app
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: todo-app-api
          image: localhost:5000/todo-app-api:0.1.0
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: mongo-host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: mongo-port
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: mongo-database
            - name: MONGO_USER
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: mongo-root-password
