apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  namespace: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    # directory location on host
    path: /mnt/data/k8s
    # this field is optional
    type: Directory
