apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  namespace: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.120
    path: "/sambashare"
